[project]
name = "djangotest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2",
    "django-debug-toolbar>=5.2.0",
    "django-extensions>=4.1",
    "pillow>=11.2.1",
    "psycopg2>=2.9.10",
]
