# Generated by Django 5.2 on 2025-04-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Скидка в %'),
        ),
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='goods',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
