# Generated by Django 5.2 on 2025-05-01 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pract', '0003_goods_discount_goods_price_goods_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='is_stock',
        ),
    ]
